NVIDIA_ROOT=	${.CURDIR}/../../..

LIB=		GLESv2_nvidia
SHLIB_VERSION=	535.154.05
SHLIB_NAME=	lib${LIB}.so.${SHLIB_VERSION}
SHLIB_LINK=	lib${LIB}.so.2
LIBDIR=		/compat/linux/usr/lib
OBJDIR=		obj/linux

.include <${NVIDIA_ROOT}/mk/nvidia.lib.mk>
