NVIDIA_ROOT=    ${.CURDIR}/../../..

LIB=		nvidia-glcore
SHLIB_VERSION=	535.129.03
SHLIB_NAME=	lib${LIB}.so.${SHLIB_VERSION}
SHLIB_NO_LINK=	1
LIBDIR=		/compat/linux/usr/lib
OBJDIR=		obj/linux

.include <${NVIDIA_ROOT}/mk/nvidia.lib.mk>
