NVIDIA_ROOT=	${.CURDIR}/../../..
OBJDIR=obj/libglvnd

.if !defined(LOCALBASE)
LOCALBASE=	/usr/local
.endif

LIB=		GLESv2
SHLIB_MAJOR=	2
LIBDIR=		${LOCALBASE}/lib

.include <${NVIDIA_ROOT}/mk/nvidia.lib.mk>
