NVIDIA_ROOT=	${.CURDIR}/../../..

LIB=		EGL_nvidia
SHLIB_VERSION=	535.129.03
SHLIB_NAME=	lib${LIB}.so.${SHLIB_VERSION}
SHLIB_LINK=	lib${LIB}.so.0
LIBDIR=		/compat/linux/usr/lib
OBJDIR=		obj/linux

.include <${NVIDIA_ROOT}/mk/nvidia.lib.mk>
