#define SMP 1
#define MAC 1
#define VIMAGE 1
#define  EARLY_AP_STARTUP  1
#define  CC_CUBIC  1
#define  NEW_PCIB  1
#define  NETLINK  1
#define SMP 1
#define MAC 1
#define VIMAGE 1
#define  EARLY_AP_STARTUP  1
#define  CC_CUBIC  1
#define  NEW_PCIB  1
#define  NETLINK  1
#define SMP 1
#define MAC 1
#define VIMAGE 1
#define  EARLY_AP_STARTUP  1
#define  CC_CUBIC  1
#define  NEW_PCIB  1
#define  NETLINK  1
#define SMP 1
#define MAC 1
#define VIMAGE 1
#define  EARLY_AP_STARTUP  1
#define  CC_CUBIC  1
#define  NEW_PCIB  1
#define  NETLINK  1
