NVIDIA_ROOT=	${.CURDIR}/../../..

LIB=		GL
SHLIB_VERSION=	1.7.0
SHLIB_NAME=	lib${LIB}.so.${SHLIB_VERSION}
SHLIB_LINK=	lib${LIB}.so.1
LIBDIR=		/compat/linux/usr/lib
OBJDIR=		obj/linux

.include <${NVIDIA_ROOT}/mk/nvidia.lib.mk>
